import { gql } from "graphql-request";
import Head from "next/head";
import Image from "next/image";
import { GetStaticProps } from "next/types";
import { useState } from "react";
import Link from 'next/link'
import MusicAlbum from "../components/MusicAlbum";
import client from "../graphql/client";
import styles from "../styles/Home.module.css";

const query = gql`
  query GetAlbumById($input: GetAlbumByIdPayload!) {
    getAlbumById(input: $input) {
      album {
        artist {
          name
          genre {
            name
            id
          }
        }
        id
        name
        imgUrl
        releaseDate
      }
    }
  }
`;

export const getServerSideProps: GetStaticProps = async () => {
  // const data = await client.request(query, {
  //   input: {
  //     id: "7c06fe54-d4e7-48b6-a9a9-c7938301b2a8",
  //   },
  // });

  return {
    props: {},
  };
};

export default function Home(props: any) {

  const [selectedMenu, setSelectedMenu] = useState()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  );
}
